version: '3'

services:
  database:
    image: postgres:9.4
    volumes:
      - dbdata:/var/lib/postgresql/data
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: database_user
      POSTGRES_PASSWORD: secret
    networks:
      - database-network

  dotnet:
    depends_on:
      - database
    build: ./docker/dotnet
    volumes:
      - ./:/app
    restart: always
    links:
      - database
    networks:
      - app-network
      - database-network

volumes:
  dbdata:

networks:
  app-network:
    driver: bridge
  database-network:
    driver: bridge
