// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NeowayTechnicianCase.Infrastructure.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace NeowayTechnicianCase.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("NeowayTechnicianCase.Core.Entities.Purchase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CPF")
                        .HasColumnType("text");

                    b.Property<bool>("CPFIsValid")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastPurchase")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double?>("LastPurchaseTicket")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("LastStoreId")
                        .HasColumnType("uuid");

                    b.Property<double?>("MediumTicket")
                        .HasColumnType("double precision");

                    b.Property<bool>("Private")
                        .HasColumnType("boolean");

                    b.Property<bool>("Unfinished")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("UsualStoreId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LastStoreId");

                    b.HasIndex("UsualStoreId");

                    b.ToTable("Purchases");
                });

            modelBuilder.Entity("NeowayTechnicianCase.Core.Entities.Store", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CNPJ")
                        .HasColumnType("text");

                    b.Property<bool>("CNPJIsValid")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Stores");
                });

            modelBuilder.Entity("NeowayTechnicianCase.Core.Entities.Purchase", b =>
                {
                    b.HasOne("NeowayTechnicianCase.Core.Entities.Store", "LastStore")
                        .WithMany()
                        .HasForeignKey("LastStoreId");

                    b.HasOne("NeowayTechnicianCase.Core.Entities.Store", "UsualStore")
                        .WithMany()
                        .HasForeignKey("UsualStoreId");

                    b.Navigation("LastStore");

                    b.Navigation("UsualStore");
                });
#pragma warning restore 612, 618
        }
    }
}
